from __future__ import annotations
from pydantic import Field
from typing import Any


from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding.coding_common import CodeFile, ProgrammingPlan
from src.models.coding.retriever import RetrievalResult
from src.models.data_manager import RegisterMapRecord

# Coder states:
# programming plan: ProgrammingPlan
# current file plan id
# retrieval result
# accepted_files: list[CodeFile]
# candidate_files: list[CodeFile]
# log: list[CoderLog]

# communicate with controller
class CoderInput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        description="programming plan for generating code",
    )

    register_maps:list[RegisterMapRecord] = Field(
        description="extracted register maps",
    )

    retrieval_results: list[RetrievalResult] = Field(
        default_factory=list,
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="not accepted code files generated by inner file coder",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="Previously accepted files, read only",
    )

class CoderOutput(StructuredOutputModel):
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="Newly created or modified candidate code files produced in this coding iteration.",
    )

    deleted_file_ids: list[str] = Field(
        default_factory=list,
        description="Identifiers of existing candidate files that should be removed from the current candidate file set."
    )

# Log
class CoderLog(StructuredOutputModel):
    coder_input: CoderInput
    coder_output: CoderOutput
    token_consumption: dict[str,Any]
