from __future__ import annotations

from typing import Any
from pydantic import Field


from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding.coding_common import CodeFile, VerificationPlan, ProgrammingPlan, InputRegisterMap
from src.models.coding.verifier import VerifierOutput
from src.models.preprocessing.function_identifier import DeviceFunctionOutput

# Planner:
## input
class PlannerInput(StructuredOutputModel):
    driver_name: str = Field(
        default = "SensorDriver",
        description="name of the driver",
    )
    device_functions:DeviceFunctionOutput = Field(
        description="Identified device functions description and involved registers from function identifier"
    )

    enable_test_coder: bool = Field(
        default=False,
        description="enable test coder",
    )
    user_request:str = Field(
        default="",
        description="user request for coding",
    )
    register_maps:list[InputRegisterMap] = Field(
        description="extracted register map",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="code files generated by the coder in previous loop",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="previous accepted candidate files",
    )
    verifier_feedback: VerifierOutput|None   = Field(
        default=None,
        description="feedback from verifier agent",
    )

## output
class PlannerOutput(StructuredOutputModel):
    plan_id: int = Field(
        description="identifier of the current plan,start from 1",
    )

    programming_plan: ProgrammingPlan = Field(
        description="programming plan for generating code",
    )

    verification_plan: VerificationPlan = Field(
        description="verification plan for the candidate files.",
    )

## log
class PlannerLog(StructuredOutputModel):
    planner_input: PlannerInput
    planner_output: PlannerOutput
    token_consumption:dict[str,Any]
