from __future__ import annotations

from typing import Any

from pydantic import Field

from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding.coding_common import CodeFile, VerificationPlan, FilePlan,InputRegisterMap
from src.models.coding.retriever import RetrievalResult

# Verifier input
class VerifierInput(StructuredOutputModel):
    verification_plan:VerificationPlan = Field(
        description="verification plan for the candidate files",
    )

    register_maps:list[InputRegisterMap] = Field(
        description= "extracted register maps",
    )

    retrieval_results:list[RetrievalResult] = Field(
        default_factory=list,
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

# Verifier output
class VerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        default=False,
        description= "true if the target file has been verified",
    )
    semantic_result: SemanticVerifierOutput = Field(
        description= "result of the semantic verification",
    )
    execution_result: ExecutionVerifierOutput= Field(
        description= "result from the compiler",
    )

# inner semantic verifier
class SemanticVerifierInput(StructuredOutputModel):
    verification_plan:str = Field(
        description="verification plan for the candidate files",
    )
    register_maps: list[InputRegisterMap] = Field(
        description="extracted register maps",
    )

    retrieval_results: list[RetrievalResult] = Field(
        default_factory=list,
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

class SemanticVerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        default=False,
        description= "true if the code pass all the verification plans.",
    )

    rejection_reasons: list[RejectionReason] = Field(
        default_factory=list,
        description= "reasons for semantic rejection. None if verification passed.",
    )

    feedback: str = Field(
        default= "",
        description="Actionable feedback for the next planning attempt. None if verification passed.",
    )

class RejectionReason(StructuredOutputModel):
    targets: list[RejectedTarget] = Field(
        default_factory=list,
        description= "target of rejected file, code section, function",
    )

    description: str = Field(
        description= "description of the rejected reason",
    )

# Compiler message
class CompilerMsg(StructuredOutputModel):
    passed: bool = Field(
        default=False,
        description= "whether the code passed or not",
    )
    compiler_message: str = Field(
        default="",
        description="compiler message. None if compilation passed",
    )

# inner execution verifier
class ExecutionVerifierInput(StructuredOutputModel):
    verification_plan:list[FilePlan] = Field(
        default_factory=list,
        description="verification plan for the candidate files",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

class ExecutionVerifierOutput(StructuredOutputModel):
    candidate_code_passed: bool = Field(
        default=False,
        description= "true if the candidate code has no syntax error",
    )

    test_code_passed: bool|None = Field(
        default=None,
        description= "true if the code and test code has no syntax errors",
    )

    test_coder_history:list[TestCoderLog] = Field(
        default_factory=list,
        description = "Detailed logs recorded by the test coder when the generated test code does not pass."
    )

    test_passed: bool|None = Field(
        default=None,
        description= "true if the candidate codes passes the test with test codes",
    )

    compiler_message: CompilerMsg = Field(
        default_factory = CompilerMsg,
        description= "compiler messages",
    )
#
class RejectedTarget(StructuredOutputModel):
    file_id: str = Field(
        default = "",
        description= "identifier of the file",
    )
    rejection_summary: str = Field(
        default="",
        description= "short rejection summary of the file with file_id. None if verification passed.",
    )

    rejected_sections: list[RejectedSection] = Field(
        default_factory=list,
        description= "rejected code sections",
    )

    rejected_functions: list[RejectedFunction] = Field(
        default_factory=list,
        description= "rejected functions",
    )

class RejectedSection(StructuredOutputModel):
    section_name: str = Field(
        default= "",
        description= "name of the rejected section",
    )

    rejection_reason: str = Field(
        default="",
        description="reason for rejection of this function. None if verification passed.",
    )

class RejectedFunction(StructuredOutputModel):
    function_name: str = Field(
        default="",
        description= "name of the rejected function",
    )
    rejection_reason: str = Field(
        default="",
        description= "reason for rejection of this function. None if verification passed.",
    )

# inner test coder input
class TestCoderConfig(StructuredOutputModel):
    verification_plan: list[FilePlan] = Field(
        default_factory=list,
    )
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
    )
class TestCoderInput(StructuredOutputModel):
    compiler_message: CompilerMsg = Field(
        default_factory=CompilerMsg,
        description="compiler messages",
    )

class TestCode(StructuredOutputModel):
    files: list[CodeFile] = Field(
        default_factory=list,
        description="test code files generated by inner coder agent",
    )

class TestCoderOutput(StructuredOutputModel):
    passed:bool = Field(
        default=False,
        description= "true if the code has no syntax errors",
    )

    files: list[CodeFile] = Field(
        default_factory=list,
        description="test code files generated by inner coder agent",
    )

    compiler_message: CompilerMsg = Field(
        default_factory=CompilerMsg,
        description="compiler message",
    )

# Log
class VerifierLog(StructuredOutputModel):
    verifier_input: VerifierInput
    verifier_output: VerifierOutput
    execution_verifier_log: ExecutionVerifierLog
    token_consumption:dict[str,Any]

class ExecutionVerifierLog(StructuredOutputModel):
    enable_test_coder: bool = Field(
        default=False,
    )
    execution_input: ExecutionVerifierInput
    execution_output: ExecutionVerifierOutput
    test_coder_logs: list[TestCoderLog]
    token_consumption: dict[str,Any]

class TestCoderLog(StructuredOutputModel):
    attempt:int = Field(
        default=0,
    )
    test_coder_input: TestCoderInput = Field(
        default_factory=TestCoderInput,
    )
    test_coder_output: TestCoderOutput = Field(
        default_factory=TestCoderOutput,
    )
