from __future__ import annotations
from pydantic import Field
from typing import Any

from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding_common import Operation,CodeFile,ProgrammingPlan
from src.models.retriever import RetrievalResult
from src.models.register_output import RegisterMapOutput

# Coder states:
# programming plan: ProgrammingPlan
# current file plan id
# retrieval result
# accepted_files: list[CodeFile]
# candidate_files: list[CodeFile]
# log: list[CoderLog]

# communicate with controller
class CoderInput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        description="programming plan for generating code",
    )

    register_map:RegisterMapOutput = Field(
        description="extracted register map",
    )

    retrieval_result: list[RetrievalResult] = Field(
        default_factory=list,
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="not accepted code files generated by inner file coder",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="Previously accepted files, read only",
    )

class CoderOutput(StructuredOutputModel):
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="Newly created or modified candidate code files produced in this coding iteration.",
    )

    deleted_file_ids: list[str] = Field(
        default_factory=list,
        description="Identifiers of existing candidate files that should be removed from the current candidate file set."
    )

    incomplete_implementation: list[IncompleteImplementation] = Field(
        default_factory=list,
        description="Planned target operations that could not be fully implemented in this coding iteration.",
    )

class IncompleteImplementation(StructuredOutputModel):
    target_file_id: str = Field(
        description="Identifier of the target file with an incomplete planned operation.",
    )

    target_section: str = Field(
        description="Name of the incomplete target section. Use an empty string if the issue is not section-specific.",
    )

    target_function: str = Field(
        description="Name of the incomplete target function. Use an empty string if the issue is not function-specific.",
    )

    description: str = Field(
        description="Description of what has been implemented so far and what remains unimplemented.",
    )

    reason: str = Field(
        description="Reason why the planned operation could not be fully implemented.",
    )
# Log
class CoderLog(StructuredOutputModel):
    coder_input: CoderInput
    coder_output: CoderOutput
    token_consumption: dict[str,Any]
