from __future__ import annotations
from pydantic import Field
from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding_common import Operation,CodeFile,ProgrammingPlan
from src.models.retriever import RetrievalResult
from src.models.register_output import RegisterMapOutput

# Coder states:
# programming plan: ProgrammingPlan
# current file plan id
# retrieval result
# accepted_files: list[CodeFile]
# candidate_files: list[CodeFile]
# log: list[CoderLog]

# communicate with controller
class CoderInput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        default = None,
        description="programming plan for generating code",
    )

    register_map:RegisterMapOutput = Field(
        description="extracted register map",
    )

    retrieval_result: list[RetrievalResult] = Field(
        default_factory=list,
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="not accepted code files generated by inner file coder",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="Previously accepted files, read only",
    )

class CoderOutput(StructuredOutputModel):
    candidate_files: list[CodeFile] = Field(
        description="code files for realisation of the programming plan",
    )

    # log: list[CoderLog] = Field(
    #     default_factory=list,
    #     description="coder log",
    # )

# class FileChangeMsg(StructuredOutputModel):
#     file_id: str = Field(
#         description="identifier of the modified file",
#     )
#     operation: Operation = Field(
#         description="operation of the modified file, the field 'operation' of this value must not be 'keep'",
#     )
#     added: str = Field(
#         description="short description of what was added into the modified file",
#     )
#     deleted: str = Field(
#         description="short description of what was deleted in the modified file",
#     )
#     modified: str = Field(
#         description="short description of what was modified in the modified file",
#     )
#
# class CoderLog(StructuredOutputModel):
#     file_plan: FilePlan = Field(
#         description="file plan created by inner file planner",
#     )
#     log: list[FileChangeMsg] = Field(
#         default_factory=list,
#         description="output commit message from inner file coder",
#     )