from __future__ import annotations
from pydantic import Field
from typing import Literal
from src.models.structuredOutputModel import StructuredOutputModel
from src.models.verifier import RejectionReason
from src.models.planner import ProgrammingPlan
from src.models.retriever import RetrievalResponse
from src.models.verifier import VerifierOutput

# Coder states:
# programming plan: ProgrammingPlan
# current file plan id
# retrieval result
# accepted_files: list[CodeFile]
# candidate_files: list[CodeFile]
# log: list[CoderLog]

# communicate with controller
class CoderInput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        description="one of the programming plans created by Planner",
    )
    retrieval_result: RetrievalResponse = Field(
        description="required infos for realisation of the programming plan",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="Previously accepted files, read only",
    )

class CoderOutput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        description="one of the programming plans created by Planner",
    )
    files: list[CodeFile] = Field(
        description="code files for realisation of the programming plan",
    )
    passed: bool = Field(
        description="whether the code files are accepted by verifier or not",
    )
    reason: list[RejectionReason] = Field(
        default_factory=list,
        description="reasons for rejection" )
    log: list[CoderLog] = Field(
        default_factory=list,
        description="coder log",
    )

# Inner file planner:
## input
class FilePlannerInput(StructuredOutputModel):
    programming_plan: ProgrammingPlan = Field(
        description="one of the programming plans created by Planner",
    )
    retrieval_result: RetrievalResponse = Field(
        description="required infos for realisation of the programming plan",
    )
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="code files generated by inner file coder",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="previous accepted code files",
    )
    verifier_feedback: VerifierOutput|None   = Field(
        default=None,
        description="feedback from verifier agent",
    )

## output
class FilePlan(StructuredOutputModel):
    file_plan_id: int
    description: str = Field(
        description="short description of the current file plan",
    )
    target_files: list[TargetFile] = Field(
        default_factory=list,
        description="files to be modified in current file plan",
    )

class TargetFile(StructuredOutputModel):
    file_id: str = Field(
        description="identifier of the current target file. when target file is a existing file, use the file id of the existing file. "
                    "otherwise create a new file id",
    )
    name: str = Field(
        description="name of the current target file",
    )
    file_type: str = Field(
        description="type of the current target file, .c or .h",
    )
    operation: Operation = Field(
        description="operation of the current target file."
                    "the field 'operation' of this value must be one of 'delete', 'modify', or 'create'."
                    "Files not listed in target_files must remain unchanged."
    )
    description: str = Field(
        description="short functional description of the current target file",
    )
    functions: list[FunctionSpec] = Field(
        default_factory=list,
        description="functions to be modified in current target file",
    )

class FunctionSpec(StructuredOutputModel):
    name:str = Field(
        description="name of the current target function",
    )
    description:str = Field(
        description="short functional description of the current target function",
    )
    operation: Operation = Field(
        description="operation of the current target function, "
                    " the field 'operation' of this value must be one of 'delete', 'modify', 'create' " ,
    )
    parameters:list[DataType] = Field(
        default_factory=list,
        description="input parameters for the target function",
    )
    return_type:DataType = Field(
        description="output type of the target function",
    )

class DataType(StructuredOutputModel):
    position:int = Field(
        description="position of the current parameter or output in the target function",
    )
    name:str = Field(
        description="name of the current parameter or output",
    )
    data_type:str = Field(
        description="data type of the current parameter or output",
    )
    description:str = Field(
        description="short description of the current parameter or output",
    )
    optional:bool = Field(
        description="whether the current parameter or output is optional",
    )

class Operation(StructuredOutputModel):
    operation: Literal["delete", "modify", "create"] = Field(
        description="Operation type.",
    )
    description: str = Field(
        description="Short description of the current operation.",
    )

# Inner file Coder
## input
class FileCoderInput(StructuredOutputModel):
    file_plan: FilePlan = Field(
        description="file plan generated by inner file planner",
    )
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )
    accepted_files:list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

## output
class FileCoderOutput(StructuredOutputModel):
    files: list[CodeFile]= Field(
        default_factory=list,
        description="Full contents of files created or modified in the current file plan. "
        "Files not returned here must remain unchanged.",
    )
    log: list[FileChangeMsg] = Field(
        default_factory=list,
        description="short message of the modification of the code files",
    )

class CodeFile(StructuredOutputModel):
    file_id: str = Field(
        description="identifier of the current code file",
    )
    name: str = Field(
        description="name of the current code file",
    )
    file_type: str = Field(
        description="type of the current code file, .c or .h",
    )
    description: str = Field(
        description="short functional description of the current code file",
    )
    content: str = Field(
        description="content of the current code file",
    )

class FileChangeMsg(StructuredOutputModel):
    file_id: str = Field(
        description="identifier of the modified file",
    )
    operation: Operation = Field(
        description="operation of the modified file, the field 'operation' of this value must not be 'keep'",
    )
    added: str = Field(
        description="short description of what was added into the modified file",
    )
    deleted: str = Field(
        description="short description of what was deleted in the modified file",
    )
    modified: str = Field(
        description="short description of what was modified in the modified file",
    )

class CoderLog(StructuredOutputModel):
    file_plan_id: int = Field(
        description="identifier of file plan",
    )
    file_plan: FilePlan = Field(
        description="file plan created by inner file planner",
    )
    log: list[FileChangeMsg] = Field(
        default_factory=list,
        description="output commit message from inner file coder",
    )
    verifier_feedback: VerifierOutput|None = Field(
        default = None,
        description="feedback from verifier agent",
    )