from __future__ import annotations

from typing import Any
from pydantic import Field

from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding_common import CodeFile,VerificationPlan,ProgrammingPlan
from src.models.verifier import VerifierOutput
from src.models.retriever import RetrievalTopic
from src.models.register_output import RegisterMapOutput

# Planner:
## input
class PlannerInput(StructuredOutputModel):
    driver_name: str = Field(
        default = "SensorDriver",
        description="name of the driver",
    )
    enable_test_coder: bool = Field(
        default=False,
        description="enable test coder",
    )
    user_request:str = Field(
        default="Generate an Arduino Wire.h-based C++ driver library with one .ino entrance file, one .h file and one .cpp file.",
        description="user request for coding",
    )
    register_map:RegisterMapOutput = Field(
        description="extracted register map",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="code files generated by the coder in previous loop",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="previous accepted candidate files",
    )
    verifier_feedback: VerifierOutput|None   = Field(
        default=None,
        description="feedback from verifier agent",
    )

## output
class PlannerOutput(StructuredOutputModel):
    plan_id: int = Field(
        description="identifier of the current plan,start from 1",
    )

    retrieval_topics: list[RetrievalTopic] = Field(
        default_factory=list,
        description="used to retrieve pages from the source files in order to supplement information "
                    "that is missing or unclear in the register map, or topics related to parts of the register map "
                    "that may be incorrect after verification.",
    )

    programming_plan: ProgrammingPlan = Field(
        description="programming plan for generating code",
    )

    verification_plan: VerificationPlan = Field(
        description="verification plan for the candidate files.",
    )

## log
class PlannerLog(StructuredOutputModel):
    planner_input: PlannerInput
    planner_output: PlannerOutput
    token_consumption:dict[str,Any]