from __future__ import annotations

from pydantic import Field
from typing import Literal

from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding_common import CodeFile,VerificationPlan,ProgrammingPlan,VerifierFeedback
from src.models.retriever import RetrievalTopic
from src.models.register_output import RegisterMapOutput

# Planner:
## input
class PlannerInput(StructuredOutputModel):
    enable_test_coder: bool = Field(
        default=False,
        description="enable test coder",
    )
    user_request:str = Field(
        default="Generate C driver",
        description="user request for coding",
    )
    register_map:RegisterMapOutput = Field(
        description="extracted register map",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="code files generated by inner file coder",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="previous accepted code files",
    )
    verifier_feedback: VerifierFeedback|None   = Field(
        default=None,
        description="feedback from verifier agent",
    )

## output
class PlannerOutput(StructuredOutputModel):
    plan_id: int = Field(
        description="identifier of the current plan,start from 1",
    )

    retrieval_topics: list[RetrievalTopic] = Field(
        default_factory=list,
        description="used to retrieve pages from the source files in order to supplement information "
                    "that is missing or unclear in the register map, or topics related to parts of the register map "
                    "that may be incorrect after verification.",
    )

    programming_plan: ProgrammingPlan = Field(
        default = None,
        description="programming plan for generating code",
    )

    verification_plan: VerificationPlan | None = Field(
        description="verification plan for the candidate files. If enable_test_coder is set to false, leave this field empty",
    )
