from __future__ import annotations
from src.models.structuredOutputModel import StructuredOutputModel
from src.models.planner import ProgrammingPlan
from src.models.retriever import RetrievalResponse
from pydantic import Field
from src.models.coder import CodeFile

# Verifier input
class VerificationRequest(StructuredOutputModel):
    programming_plan:ProgrammingPlan = Field(
        description= "one of the programming plans created by Planner",
    )
    retrieval_result:RetrievalResponse = Field(
        description="required infos for realisation of the programming plan",
    )
    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )
    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

# Verifier output
class VerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the target file has been verified",
    )
    semantic_result: SemanticVerificationResult = Field(
        description= "result of the semantic verification",
    )
    execution_result: ExecutionResult = Field(
        description= "result from the compiler",
    )
    feedback: str = Field(
        description="Actionable feedback for the next file planning attempt. None if verification passed.",
    )

# inner semantic verifier
class SemanticVerificationResult(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the code semantically matches the programming plan.",
    )
    rejection_reason: RejectionReason = Field(
        description= "reason for semantic rejection. None if verification passed.",
    )
# inner execution verifier
class ExecutionResult(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the code has no syntax errors",
    )
    rejection_reason: RejectionReason = Field(
        description= "reason for execution rejection. None if verification passed.",
    )
    compiler_message: str = Field(
        description= "compiler message",
    )
# ...
class RejectionReason(StructuredOutputModel):
    rejected_files: list[RejectedFile] = Field(
        description= "Rejected files",
    )

class RejectedFile(StructuredOutputModel):
    file_id: str = Field(
        description= "identifier of the file",
    )
    rejection_summary: str = Field(
        description= "short rejection summary of the file with file_id. None if verification passed.",
    )
    functions: list[RejectedFunction] = Field(
        description= "rejected functions",
    )

class RejectedFunction(StructuredOutputModel):
    function_name: str = Field(
        description= "name of the rejected function",
    )
    rejection_reason: str = Field(
        description= "reason for rejection of this function. None if verification passed.",
    )
