from __future__ import annotations

from pydantic import Field

from src.models.structuredOutputModel import StructuredOutputModel
from src.models.coding_common import CodeFile,VerificationPlan,FilePlan
from src.models.retriever import RetrievalResult
from src.models.register_output import RegisterMapOutput

# Verifier input
class VerifierInput(StructuredOutputModel):
    verification_plan:VerificationPlan = Field(
        description="verification plan for the candidate files",
    )

    register_map:RegisterMapOutput = Field(
        description= "extracted register map",
    )

    retrieval_results:list[RetrievalResult] = Field(
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

# Verifier output
class VerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the target file has been verified",
    )
    semantic_result: SemanticVerifierOutput = Field(
        description= "result of the semantic verification",
    )
    execution_result: ExecutionVerifierOutput= Field(
        description= "result from the compiler",
    )

# inner semantic verifier
class SemanticVerifierInput(StructuredOutputModel):
    verification_plan:str = Field(
        description="verification plan for the candidate files",
    )
    register_map: RegisterMapOutput = Field(
        description="extracted register map",
    )

    retrieval_results: list[RetrievalResult] = Field(
        description="required infos for realisation of the programming plan",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

class SemanticVerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the code pass all the verification plans.",
    )

    rejection_reasons: list[RejectionReason] = Field(
        description= "reasons for semantic rejection. None if verification passed.",
    )

    feedback: str = Field(
        description="Actionable feedback for the next planning attempt. None if verification passed.",
    )

class RejectionReason(StructuredOutputModel):
    targets: list[RejectedTarget] = Field(
        description= "target of rejected file, code section, function",
    )

    description: str = Field(
        description= "description of the rejected reason",
    )

# inner execution verifier
class ExecutionVerifierInput(StructuredOutputModel):
    verification_plan:list[FilePlan] = Field(
        description="verification plan for the candidate files",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

class ExecutionVerifierOutput(StructuredOutputModel):
    passed: bool = Field(
        description= "true if the code has no syntax errors",
    )
    compiler_message: CompilerMsg = Field(
        description= "compiler messages",
    )
#
class RejectedTarget(StructuredOutputModel):
    file_id: str = Field(
        description= "identifier of the file",
    )
    rejection_summary: str = Field(
        description= "short rejection summary of the file with file_id. None if verification passed.",
    )

    rejected_sections: list[RejectedSection] = Field(
        description= "rejected code sections",
    )

    functions: list[RejectedFunction] = Field(
        description= "rejected functions",
    )

class RejectedSection(StructuredOutputModel):
    section_name: str = Field(
        description= "name of the rejected section",
    )

    rejection_reason: str = Field(
        description="reason for rejection of this function. None if verification passed.",
    )

class RejectedFunction(StructuredOutputModel):
    function_name: str = Field(
        description= "name of the rejected function",
    )
    rejection_reason: str = Field(
        description= "reason for rejection of this function. None if verification passed.",
    )

# inner test coder input
class TestCoderInput(StructuredOutputModel):
    verification_plan: str = Field(
        description="verification plan for the candidate files",
    )

    candidate_files: list[CodeFile] = Field(
        default_factory=list,
        description="candidate code files generated by inner coder agent",
    )

    accepted_files: list[CodeFile] = Field(
        default_factory=list,
        description="accepted files from previous as reference in current file plan, read only",
    )

    compiler_message: CompilerMsg = Field(
        description="compiler messages",
    )

class TestCoderOutput(StructuredOutputModel):
    files: list[CodeFile] = Field(
        default_factory=list,
        description="test code files generated by inner coder agent",
    )

class CompilerMsg(StructuredOutputModel):
    passed: bool = Field(
        description= "whether the code passed or not",
    )
    compiler_message: str = Field(
        description="compiler message. None if compilation passed",
    )